name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Workflow
    uses: action-stars/generic-workflows/.github/workflows/release.yaml@b24ecde8300098d02a88de7eb886ebb65845e6fa # v0.3.2
    permissions:
      contents: write
